site_name: ETL de Excel - Workshop 1
theme:
  name: material # or other theme
  palette:
    primary: blue
  language: pt

repo_name: "SamuelNatividade/workshop1"
repo_url: "https://github.com/SamuelNatividade/workshop1"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python